# ~/.tmuxinator.yml
name: e-bpm
root: ~/Workspace/e-bpm/

windows:
  # client
  - client:
      root: e-bpm-client
      layout: main-vertical
      panes:
        - develop: gatsby develop
  
  # server
  - server:
      root: e-bpm
      layout: main-vertical
      panes:
        - develop: air